---
name: Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

env:
  PROJECT_NAME: maps
  BUILD_DIR: app/dist

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # ---------- build ----------
      - name: Setup node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "18.17.1"
      - name: "Install requirements - app"
        working-directory: app
        run: npm install
      - name: "Install requirements - styles"
        working-directory: styles
        run: npm install
      - name: Build app
        working-directory: app
        run: npm run build
      # ---------- publish ----------
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ${{ env.BUILD_DIR }} --project-name=${{ env.PROJECT_NAME }}
